const USER_REGISTER_START = 'USER_REGISTER_START'
const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
const ERROR_SET_SUCCESS = 'ERROR_SET_SUCCESS'

export {
  USER_REGISTER_START,
  USER_REGISTER_SUCCESS,
  USER_REGISTER_FAIL,
  ERROR_SET_SUCCESS,
}
