const USER_REGISTER_START = 'USER_REGISTER_START'
const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
const USER_LOGIN_START = 'USER_LOGIN_START'
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
const USER_LOGOUT = 'USER_LOGOUT'

const ADD_DOUBT_START = 'ADD_DOUBT_START'
const ADD_DOUBT_SUCCESS = 'ADD_DOUBT_SUCCESS'
const ADD_DOUBT_FAIL = 'ADD_DOUBT_FAIL'

const ERROR_SET_SUCCESS = 'ERROR_SET_SUCCESS'

export {
  USER_REGISTER_START,
  USER_REGISTER_SUCCESS,
  USER_REGISTER_FAIL,
  USER_LOGIN_START,
  USER_LOGIN_SUCCESS,
  USER_LOGIN_FAIL,
  USER_LOGOUT,
  ADD_DOUBT_START,
  ADD_DOUBT_SUCCESS,
  ADD_DOUBT_FAIL,
  ERROR_SET_SUCCESS,
}
